[package]
name = "pre_email_demo"
version = "0.1.0"
authors = ["Janik Dohrmann <janik.dohrmann@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recrypt = "0.12.0"
imap = "2.4.1"
native-tls = "0.2.7"