//
// email
// Author: Janik
//

ALPHA = _{ 'a'..'z' | 'A'..'Z' }
DIGIT = _{ '0'..'9' }

AT = _{ "@" }
PAREN = _{"\""}
ANGLEBRACKETLEFT = _{"<"}
ANGLEBRACKETRIGHT = _{">"}
DOT = _{"."}

alia = {(ALPHA | DIGIT)+}
address = { (ALPHA | DIGIT)+ ~ AT ~ (ALPHA | DIGIT | DOT)+}

from = {"From: " ~ (PAREN ~ alia ~ PAREN)? ~ ANGLEBRACKETLEFT ~ address ~ ANGLEBRACKETRIGHT}

text = {(ALPHA | DIGIT | " " | "-")+}
subject = {"Subject: " ~ text}

WHITESPACE = _{" " | "\t" | "\n" | "\r" }