name: PRE-Demontrator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-proxy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --manifest-path ./proxy/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ./proxy/Cargo.toml --verbose
      
  test-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --manifest-path ./client/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ./client/Cargo.toml --verbose
